export const HeaderMenu = [
  {
    label: "Homes",
    imageUrl: "/images/home.avif",
    path: "/",
  },
  {
    label: "Experiences",
    imageUrl: "/images/parachute.avif",
    path: "/experiences",
  },
  {
    label: "Services",
    imageUrl: "/images/bell.avif",
    path: "/services",
  },
];

export const MIDDOT = "\u00B7";

export const HomePageListingsGroupInfo = [
  {
    location: "Helsinki",
    header: "Homes around Finland",
    listings: [
      {
        id: 1,
        title: "Stylish apartment in center of the city",
        price: 120,
        imageUrl: "/images/1.jpg",
        hostType: "Superhost",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Great location!", rating: 5 },
          { id: 2, comment: "Very clean and comfortable.", rating: 4 },
          { id: 3, comment: "Would stay again.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 2,
        title: "Cozy studio near the park",
        price: 80,
        imageUrl: "/images/2.png",
        hostType: "Host",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Nice place", rating: 4 },
          { id: 2, comment: "Could be better", rating: 3 },
          { id: 3, comment: "Loved it!", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 3,
        title: "Modern flat with city views",
        price: 150,
        imageUrl: "/images/3.png",
        hostType: "Superhost",
        listingType: "Room",
        reviews: [
          { id: 1, comment: "Great stay!", rating: 5 },
          { id: 2, comment: "Very nice host.", rating: 4 },
          { id: 3, comment: "Would come again.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 8,
        title: "Luxury penthouse suite",
        price: 300,
        imageUrl: "/images/4.webp",
        hostType: "Superhost",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Absolutely stunning!", rating: 5 },
          { id: 2, comment: "Best experience ever.", rating: 5 },
          { id: 3, comment: "Will book again.", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 9,
        title: "Budget-friendly room",
        price: 60,
        imageUrl: "/images/5.avif",
        hostType: "Host",
        listingType: "Room",
        reviews: [
          { id: 1, comment: "Good value for money.", rating: 4 },
          { id: 2, comment: "Decent stay.", rating: 3 },
          { id: 3, comment: "Would recommend.", rating: 4 },
        ],
        guestFavorite: false,
      },
      {
        id: 10,
        title: "Family-friendly house",
        price: 220,
        imageUrl: "/images/33.jpeg",
        hostType: "Superhost",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Perfect for our family!", rating: 5 },
          { id: 2, comment: "Spacious and clean.", rating: 4 },
          { id: 3, comment: "Would stay again.", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 11,
        title: "Chic loft in trendy neighborhood",
        price: 180,
        imageUrl: "/images/7.jpg",
        hostType: "Host",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Loved the location!", rating: 5 },
          { id: 2, comment: "Very stylish place.", rating: 4 },
          { id: 3, comment: "Would visit again.", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 12,
        title: "Quiet retreat near nature",
        price: 140,
        imageUrl: "/images/8.jpg",
        hostType: "Superhost",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Peaceful and quiet.", rating: 5 },
          { id: 2, comment: "Loved the nature around.", rating: 4 },
          { id: 3, comment: "Perfect getaway!", rating: 5 },
        ],
        guestFavorite: true,
      },
    ],
  },
  {
    location: "Oslo",
    header: "Homes around Oslo",
    listings: [
      {
        id: 4,
        title: "Charming house by the river",
        price: 200,
        imageUrl: "/images/9.jpeg",
        hostType: "Superhost",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Beautiful location!", rating: 5 },
          { id: 2, comment: "Very comfortable stay.", rating: 4 },
          { id: 3, comment: "Would love to come back.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 5,
        title: "Spacious villa with garden",
        price: 250,
        imageUrl: "/images/10.jpeg",
        hostType: "Host",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Amazing garden!", rating: 5 },
          { id: 2, comment: "Great for families.", rating: 4 },
          { id: 3, comment: "Would stay again.", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 6,
        title: "Comfortable apartment in downtown",
        price: 130,
        imageUrl: "/images/11.jpeg",
        hostType: "Superhost",
        listingType: "Room",
        reviews: [
          { id: 1, comment: "Perfect location!", rating: 5 },
          { id: 2, comment: "Very cozy place.", rating: 4 },
          { id: 3, comment: "Would recommend.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 13,
        title: "Modern condo with amenities",
        price: 160,
        imageUrl: "/images/12.jpeg",
        hostType: "Host",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Loved the amenities!", rating: 5 },
          { id: 2, comment: "Very modern and clean.", rating: 4 },
          { id: 3, comment: "Would visit again.", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 14,
        title: "Cozy cabin in the mountains",
        price: 190,
        imageUrl: "/images/14.jpeg",
        hostType: "Superhost",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Amazing place!", rating: 5 },
          { id: 2, comment: "Very comfortable.", rating: 4 },
          { id: 3, comment: "Would visit again.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 15,
        title: "Luxury apartment with skyline views",
        price: 280,
        imageUrl: "/images/15.jpeg",
        hostType: "Host",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Stunning views!", rating: 5 },
          { id: 2, comment: "Very luxurious.", rating: 4 },
          { id: 3, comment: "Would stay again.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 16,
        title: "Affordable room in shared flat",
        price: 70,
        imageUrl: "/images/16.jpeg",
        hostType: "Superhost",
        listingType: "Room",
        reviews: [
          { id: 1, comment: "Good value for money.", rating: 4 },
          { id: 2, comment: "Decent stay.", rating: 3 },
          { id: 3, comment: "Would recommend.", rating: 4 },
        ],
        guestFavorite: false,
      },
      {
        id: 17,
        title: "Family home near attractions",
        price: 210,
        imageUrl: "/images/17.jpeg",
        hostType: "Host",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Perfect for our family!", rating: 5 },
          { id: 2, comment: "Spacious and clean.", rating: 4 },
          { id: 3, comment: "Would stay again.", rating: 5 },
        ],
        guestFavorite: false,
      },
    ],
  },
  {
    location: "Oulu",
    header: "Homes around Oulu",
    listings: [
      {
        id: 7,
        title: "Cozy cabin in the woods",
        price: 180,
        imageUrl: "/images/18.jpeg",
        hostType: "Superhost",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Loved the nature!", rating: 5 },
          { id: 2, comment: "Very peaceful stay.", rating: 4 },
          { id: 3, comment: "Would come back.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 18,
        title: "Downtown apartment with balcony",
        price: 140,
        imageUrl: "/images/18.jpeg",
        hostType: "Superhost",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Great location!", rating: 5 },
          { id: 2, comment: "Very comfortable.", rating: 4 },
          { id: 3, comment: "Would stay again.", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 19,
        title: "Beachfront villa with pool",
        price: 320,
        imageUrl: "/images/19.jpeg",
        hostType: "Host",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Amazing views!", rating: 5 },
          { id: 2, comment: "Loved the pool.", rating: 4 },
          { id: 3, comment: "Would visit again.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 20,
        title: "Charming studio in historic area",
        price: 110,
        imageUrl: "/images/20.jpeg",
        hostType: "Superhost",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Great location!", rating: 5 },
          { id: 2, comment: "Very cozy and clean.", rating: 4 },
          { id: 3, comment: "Would recommend.", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 21,
        title: "Spacious loft with modern decor",
        price: 170,
        imageUrl: "/images/21.jpeg",
        hostType: "Host",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Loved the decor!", rating: 5 },
          { id: 2, comment: "Very spacious.", rating: 4 },
          { id: 3, comment: "Would stay again.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 22,
        title: "Quiet countryside retreat",
        price: 160,
        imageUrl: "/images/22.jpeg",
        hostType: "Superhost",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Peaceful and relaxing.", rating: 5 },
          { id: 2, comment: "Beautiful surroundings.", rating: 4 },
          { id: 3, comment: "Perfect getaway!", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 23,
        title: "Affordable studio near university",
        price: 90,
        imageUrl: "/images/23.jpeg",
        hostType: "Host",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Great for students!", rating: 4 },
          { id: 2, comment: "Good value for money.", rating: 4 },
          { id: 3, comment: "Would recommend.", rating: 4 },
        ],
        guestFavorite: false,
      },
      {
        id: 24,
        title: "Luxury home with private garden",
        price: 270,
        imageUrl: "/images/24.jpeg",
        hostType: "Superhost",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Absolutely stunning!", rating: 5 },
          { id: 2, comment: "Loved the garden.", rating: 5 },
          { id: 3, comment: "Will book again.", rating: 5 },
        ],
        guestFavorite: true,
      },
    ],
  },
  {
    location: "Rovaniemi",
    header: "Homes around Rovaniemi",
    listings: [
      {
        id: 25,
        title: "Winter cabin with fireplace",
        price: 200,
        imageUrl: "/images/25.jpeg",
        hostType: "Superhost",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Cozy and warm.", rating: 5 },
          { id: 2, comment: "Perfect for winter.", rating: 4 },
          { id: 3, comment: "Would love to return.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 26,
        title: "City center apartment",
        price: 130,
        imageUrl: "/images/32.jpeg",
        hostType: "Host",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Great location!", rating: 5 },
          { id: 2, comment: "Very comfortable.", rating: 4 },
          { id: 3, comment: "Would stay again.", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 27,
        title: "Cozy room in shared flat",
        price: 75,
        imageUrl: "/images/27.jpeg",
        hostType: "Superhost",
        listingType: "Room",
        reviews: [
          { id: 1, comment: "Good value for money.", rating: 4 },
          { id: 2, comment: "Decent stay.", rating: 3 },
          { id: 3, comment: "Would recommend.", rating: 4 },
        ],
        guestFavorite: false,
      },
      {
        id: 28,
        title: "Luxury villa with sauna",
        price: 300,
        imageUrl: "/images/28.jpeg",
        hostType: "Superhost",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Amazing experience!", rating: 5 },
          { id: 2, comment: "Loved the sauna.", rating: 5 },
          { id: 3, comment: "Will book again.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 29,
        title: "Charming cottage near lake",
        price: 180,
        imageUrl: "/images/29.jpeg",
        hostType: "Host",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Beautiful location!", rating: 5 },
          { id: 2, comment: "Very relaxing stay.", rating: 4 },
          { id: 3, comment: "Would come back.", rating: 5 },
        ],
        guestFavorite: false,
      },
      {
        id: 30,
        title: "Modern studio with amenities",
        price: 120,
        imageUrl: "/images/30.jpeg",
        hostType: "Superhost",
        listingType: "Entire apartment",
        reviews: [
          { id: 1, comment: "Loved the amenities!", rating: 5 },
          { id: 2, comment: "Very modern and clean.", rating: 4 },
          { id: 3, comment: "Would visit again.", rating: 5 },
        ],
        guestFavorite: true,
      },
      {
        id: 31,
        title: "Family-friendly home",
        price: 220,
        imageUrl: "/images/31.jpeg",
        hostType: "Host",
        listingType: "Entire house",
        reviews: [
          { id: 1, comment: "Perfect for our family!", rating: 5 },
          { id: 2, comment: "Spacious and clean.", rating: 4 },
          { id: 3, comment: "Would stay again.", rating: 5 },
        ],
        guestFavorite: false,
      },
    ],
  },
];
